WebBookProject/WebBookProject/Models/Publisher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebBookProject.Models
{
    public class Publisher
    {
        public int PublisherId { get; set; }
        public string PublisherName { get; set; }
    }
}

WebBookProject/WebBookProject/Areas/Admin/Controllers/PublishersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBookProject.Data;
using WebBookProject.Models;

namespace WebBookProject.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class PublishersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PublishersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Publishers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Publisher.ToListAsync());
        }

        // GET: Publishers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publisher
                .FirstOrDefaultAsync(m => m.PublisherId == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // GET: Publishers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Publishers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PublisherId,PublisherName")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(publisher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Publishers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publisher.FindAsync(id);
            if (publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }

        // POST: Publishers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PublisherId,PublisherName")] Publisher publisher)
        {
            if (id != publisher.PublisherId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(publisher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PublisherExists(publisher.PublisherId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Publishers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publisher
                .FirstOrDefaultAsync(m => m.PublisherId == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // POST: Publishers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var publisher = await _context.Publisher.FindAsync(id);
            _context.Publisher.Remove(publisher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PublisherExists(int id)
        {
            return _context.Publisher.Any(e => e.PublisherId == id);
        }
    }
}

WebBookProject/WebBookProject/Areas/Admin/Views/Publishers/Create.cshtml
@model WebBookProject.Models.Publisher

@{
    ViewData["Title"] = "Create";
}

<h1>Yayınevi Ekle</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PublisherName" class="control-label">Yayınevi</label>
                <input asp-for="PublisherName" class="form-control" />
                <span asp-validation-for="PublisherName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Ekle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Geri Dön</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebBookProject/WebBookProject/Areas/Admin/Views/Publishers/Delete.cshtml
@model WebBookProject.Models.Publisher

@{
    ViewData["Title"] = "Delete";
}

<h1>Yayınevi Sil</h1>

<h3>Silmek istediğinize emin misiniz?</h3>
<div>
    <h4>Yayınevi</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublisherName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublisherName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PublisherId" />
        <input type="submit" value="Sil" class="btn btn-danger" /> |
        <a class="btn btn-info" asp-action="Index">Geri Dön</a>
    </form>
</div>

WebBookProject/WebBookProject/Areas/Admin/Views/Publishers/Details.cshtml
@model WebBookProject.Models.Publisher

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Publisher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublisherName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublisherName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PublisherId">Edit</a> |
    <a class="btn btn-info" asp-action="Index">Geri Dön</a>
</div>

WebBookProject/WebBookProject/Areas/Admin/Views/Publishers/Edit.cshtml
@model WebBookProject.Models.Publisher

@{
    ViewData["Title"] = "Yayınevi Düzenle";
}

<h1>Yayınevi Düzenle</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PublisherId" />
            <div class="form-group">
                <label asp-for="PublisherName" class="control-label">Yayınevi</label>
                <input asp-for="PublisherName" class="form-control" />
                <span asp-validation-for="PublisherName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Geri Dön</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebBookProject/WebBookProject/Areas/Admin/Views/Publishers/Index.cshtml
@model IEnumerable<WebBookProject.Models.Publisher>

@{
    ViewData["Title"] = "Yayınevi";
    Layout = "~/Views/Shared/_SidebarLayout.cshtml";

}

<h1>Yayınevleri</h1>

<p>
    <a class="btn btn-primary" style="color:white" asp-area="Admin" asp-controller="Publishers" asp-action="Create">Yayınevi Ekle</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Yayınevi Adı
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PublisherName)
                </td>
                <td>
                    <a class="btn btn-success" style="color:white" asp-action="Edit" asp-route-id="@item.PublisherId">Düzenle</a>
                </td>
                <td>
                    <a class="btn btn-dark" style="color:white" asp-action="Details" asp-route-id="@item.PublisherId">Detaylar</a>
                </td>
                <td>
                    <a class="btn btn-danger" style="color:white" asp-action="Delete" asp-route-id="@item.PublisherId">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>