WebBookProject/WebBookProject/Areas/Admin/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBookProject.Data;
using WebBookProject.Models;

namespace WebBookProject.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BooksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Book.Include(b => b.Author).Include(b => b.Category).Include(b => b.Publisher);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .Include(b => b.Category)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            List<SelectListItem> categories = (from x in _context.Category.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = x.CategoryName,
                                                   Value = x.CategoryId.ToString()
                                               }).ToList();
            ViewBag.Category = categories;

            List<SelectListItem> publishers = (from x in _context.Publisher.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = x.PublisherName,
                                                   Value = x.PublisherId.ToString()
                                               }).ToList();
            ViewBag.Publisher = publishers;

            List<SelectListItem> authors = (from x in _context.Author.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = x.AuthorName+" "+x.AuthorLastname,
                                                   Value = x.AuthorId.ToString()
                                               }).ToList();
            ViewBag.Author = authors;
            ViewData["AuthorId"] = new SelectList(_context.Author, "AuthorId", "AuthorId");
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId");
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "PublisherId", "PublisherId");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookId,BookName,publishYear,Description,ImageUrl,CategoryId,PublisherId,AuthorId")] AddBook book)
        {

            Book newBook = new Book();
            if (book.ImageUrl != null)
            {
                var extension = Path.GetExtension(book.ImageUrl.FileName);
                var newImageName = Guid.NewGuid() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Photos/", newImageName);
                var stream = new FileStream(location, FileMode.Create);
                book.ImageUrl.CopyTo(stream);
                newBook.ImageUrl = newImageName;
            }
            newBook.BookName = book.BookName;
            newBook.Author = book.Author;
            newBook.AuthorId = book.AuthorId;
            newBook.Category = book.Category;
            newBook.CategoryId = book.CategoryId;
            newBook.Description = book.Description;
            newBook.Publisher = book.Publisher;
            newBook.PublisherId = book.PublisherId;
            newBook.publishYear = book.publishYear;
           // if (ModelState.IsValid)
           // {
                _context.Add(newBook);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            // }
            List<SelectListItem> categories = (from x in _context.Category.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = x.CategoryName,
                                                   Value = x.CategoryId.ToString()
                                               }).ToList();
            ViewBag.Category = categories;

            List<SelectListItem> publishers = (from x in _context.Publisher.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = x.PublisherName,
                                                   Value = x.PublisherId.ToString()
                                               }).ToList();
            ViewBag.Publisher = publishers;

            List<SelectListItem> authors = (from x in _context.Author.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.AuthorName +"  "+ x.AuthorLastname,
                                                Value = x.AuthorId.ToString()
                                            }).ToList();
            ViewBag.Author = authors;
            ViewData["AuthorId"] = new SelectList(_context.Author, "AuthorId", "AuthorId", book.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", book.CategoryId);
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "PublisherId", "PublisherId", book.PublisherId);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Author, "AuthorId", "AuthorId", book.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", book.CategoryId);
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "PublisherId", "PublisherId", book.PublisherId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookId,BookName,publishYear,Description,ImageUrl,CategoryId,PublisherId,AuthorId")] Book book)
        {
            if (id != book.BookId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Author, "AuthorId", "AuthorId", book.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", book.CategoryId);
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "PublisherId", "PublisherId", book.PublisherId);
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .Include(b => b.Category)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Book.FindAsync(id);
            _context.Book.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Book.Any(e => e.BookId == id);
        }

WebBookProject/WebBookProject/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBookProject.Data;
using WebBookProject.Models;

namespace WebBookProject.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,CategoryName")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.CategoryId == id);
        }
    }
}

WebBookProject/WebBookProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.Extensions.Localization

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject IStringLocalizer<lang> lang


    <!doctype html>
    <html lang="en">
    <head>
        <title>Lotus Kitap</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


        <link href="~/website-menu-13/css/animate.css" rel="stylesheet" />
        <link href="~/website-menu-13/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/website-menu-13/css/style.css" rel="stylesheet" />

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar ftco_navbar bg-light ftco-navbar-light" id="ftco-navbar">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="img-responsive2" src="~/Navbar/lotus.png"
                         asp-area="" asp-controller="Home" asp-action="Index" style=" width: 65px;"><small style="color:black"><b>Lotus Kitap</b></small>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span> Menu
                </button>
                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@lang["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListCategories" asp-action="ListCategory">@lang["Category"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListBooks" asp-action="ListBook">@lang["Book"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListAuthors" asp-action="ListAuthor">@lang["Author"]</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@lang["Languages"]</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                <a class="dropdown-item" asp-route-culture="tr-TR">@lang["Turkish"]</a>
                                <a class="dropdown-item" asp-route-culture="en-US">@lang["English"]</a>
                            </div>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown04">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Categories" asp-action="Index">@lang["Categories"]</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Books" asp-action="Index">@lang["Books"]</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Publishers" asp-action="Index">@lang["Publishers"]</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Authors" asp-action="Index">@lang["Authors"]</a>
                                </div>
                            </li>
                        }

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <div class="header__top__right__auth">
                                    <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">@lang["Welcome"], @User.Identity.Name!</a>
                                </div>
                                <div class="header__top__right__auth">
                                    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                        <button type="submit" class="nav-link btn text-dark">@lang["Logout"]</button>
                                    </form>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <div class="header__top__right__auth">
                                    <a asp-area="Identity" asp-page="/Account/Register"><i class="fa fa-user"></i><i> </i>@lang["Register"]<i>  </i> </a>
                                    </div>
                                <div class="header__top__right__auth">
                                    <a asp-area="Identity" asp-page="/Account/Login"><i>  </i><i class="fa fa-sign-in"></i><i> </i>@lang["Login"]</a>
                                </div>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>


        <footer class="footer text-muted">
            <div class="container">
                &copy; 2021 - Lotus Kitap - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

        <script src="~/website-menu-13/js/main.js"></script>
        <script src="~/website-menu-13/js/bootstrap.min.js"></script>
        <script src="~/website-menu-13/js/popper.js"></script>
        <script src="~/website-menu-13/js/jquery.min.js"></script>

        @await RenderSectionAsync("Scripts", required: false)

    </body>
</html>

WebBookProject/WebBookProject/Views/Shared/_SidebarLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/Sidebar/sidebar.css" rel="stylesheet" />

<body>
<div class="sidebar-container">
    <div class="sidebar-logo">
        Admin Panel
    </div>
    <ul class="sidebar-navigation">
        <li>
            <a href="/Home/Index">
                Ana Sayfa
            </a>
        </li>
        <li>
            <a asp-area="Admin" asp-controller="Books" asp-action="Index">
               Kitap
            </a>
        </li>
        <li>
            <a asp-area="Admin" asp-controller="Categories" asp-action="Index">
               Kategori
            </a>
        </li>
        <li>
            <a asp-area="Admin" asp-controller="Publishers" asp-action="Index">
                Yayınevi
            </a>
        </li>
        <li>
            <a asp-area="Admin" asp-controller="Authors" asp-action="Index">
                 Yazar
            </a>
        </li>
    </ul>
</div>

<div class="content-container">

    <div class="container-fluid">

        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

    </div>
</div>

@RenderSection("scripts", required: false)
</body>


<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>